# Generated by Django 3.2.7 on 2021-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
