# Generated by Django 3.2.7 on 2021-11-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
