# Generated by Django 3.2.7 on 2021-11-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='identifier',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
