# Generated by Django 3.2.7 on 2021-11-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20211116_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
