# Generated by Django 3.2.7 on 2021-11-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_responses_obtained_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_submitted', to='tests.test'),
        ),
    ]
