# Generated by Django 3.2.7 on 2021-11-18 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_remove_responses_test_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='test1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test1', to='tests.test'),
        ),
    ]
