# Generated by Django 3.2.7 on 2021-11-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_responses_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetails',
            name='selections',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
